name: Suricata Check

on:
  pull_request:
    branches: ["main", "master"]
  push:
    branches: ["main", "master"]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  suricata-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Koen1999/suricata-check-action@v1.0
